- ButtplugUWPBluetoothManager/ButtplugUWPBluetoothManager.csproj
- ButtplugUWPGamepadManager/ButtplugUWPGamepadManager.csproj
This means that whilst you must have the Windows 10 SDK
(specifically 10.0.15063.0) installed in the default location of
C:\Program Files (x86)\Windows Kits\10\UnionMetadata\10.0.15063.0,
everything should build regardless of where the project is located
in your filesystem.
> Updating relative paths to Windows 10 SDK to absolute paths.

- .gitmodules
- Buttplug/Buttplug.csproj
- Buttplug/Core/ButtplugJSONMessageParser.cs
- Buttplug/packages.config
This change adds the buttplug repo as a submodule at buttplug-schema and sets the schema an an embedded resource. It uses the Newtonsoft Json.Net Schema library to perform the validation (satisfying #79). Unfortunately, there is a bug in the schema that will case the tests to fail, so the submodule will probably need to be updated once https://github.com/metafetish/buttplug/pull/15 has been accepted.
> Adding schema checking

- Buttplug/Core/ButtplugJSONMessageParser.cs
- Buttplug/Core/ButtplugLog.cs
- Buttplug/Core/IButtplugLog.cs
- ButtplugTest/Core/TestService.cs
- ButtplugTest/Messages/ButtplugMessage.cs
This flag prevents the messages from being sent over the wire, back to the client.
Handy for cases where this might cause a log recursion or when you want to log
something that might be considered too sensitive for the client.
Issue #91
> Adding a localOnly flag to the logging methods

- Buttplug/Bluetooth/Devices/FleshlightLaunch.cs
- Buttplug/Bluetooth/Devices/Kiiroo.cs
- Buttplug/Bluetooth/Devices/Lovense.cs
- Buttplug/Bluetooth/Devices/VorzeA10Cyclone.cs
- Buttplug/Core/ButtplugDevice.cs
- Buttplug/Core/ButtplugJSONMessageParser.cs
- Buttplug/Core/ButtplugLog.cs
- Buttplug/Core/ButtplugService.cs
- Buttplug/Core/DeviceManager.cs
- Buttplug/Core/IButtplugLog.cs
- Buttplug/Messages/Messages.cs
- ButtplugTest/Core/ButtplugServerTests.cs
- ButtplugUWPBluetoothManager/Core/UWPBluetoothDeviceInterface.cs
- ButtplugUWPGamepadManager/Devices/UWPGamepadDevice.cs
- ButtplugXInputGamepadManager/Devices/XInputGamepadDevice.cs
The aviable values of ErrorCode are contained in the  Error.ErrorClass enum. All existing uses have been updated to send the appropriate codes.
Issue #96
> Adding the ErrorCode field to the error messages

- Buttplug/Bluetooth/BluetoothSubtypeManager.cs
- Buttplug/Bluetooth/Devices/Lovense.cs
The Lovense Edge uses the same commands as the other lovense
revisions, but requires new service/characteristics UUID and a name.
To support all 3 revisions of Lovense hardware, 2 IBluetoothDeviceInfo
classes are added. This should hopefully let us support everything we
have device names for at the moment. Only released toy we don't
support is the Ambi, which we need a device name for.
Fixes #105
> feat: Add Lovense Edge support, break Lovense Info into revisions

- ButtplugWebsockets/ButtplugWebsocketServer.cs
- ButtplugWebsockets/ButtplugWebsocketServerBehavior.cs
This change removes the use of the deprecated AddWebSocketService, using AddService instead.
The server is also configured to listen on just a port now, meaning it should trigger the Windows Firewall to prompt to ask on which networks it should be allowed to start listening on.
> Tweaking the websocketserver usage

- Buttplug/Core/ButtplugService.cs
Just returns an Ok, so that clients that want to implement ping now
will be ready when we have the actual rules in.
Affects #81
> feat: Add ping message handling to ButtplugService

- ButtplugServerGUI/ButtplugConfig.cs
- ButtplugServerGUI/ButtplugServerGUI.csproj
- ButtplugServerGUI/MainWindow.xaml.cs
- ButtplugServerGUI/WebsocketServerControl.xaml
- ButtplugServerGUI/WebsocketServerControl.xaml.cs
- ButtplugServerGUI/packages.config
- ButtplugWebsockets/ButtplugWebsocketServer.cs
- ButtplugWebsockets/ButtplugWebsockets.csproj
- ButtplugWebsockets/CertUtils.cs
- ButtplugWebsockets/packages.config
- LICENSE
Now you can use the WebSocket from JS hosted on a page severed over HTTPS (point the client at wss://127.0.0.1/buttplug)
This change adds cert generation (a self signed CA and a child cert) and stores them in %appdata%\Buttplug. The existing cert is loaded into the WebSocketServer if one already exists.
The GUI has been updated to you can now specify the port Buttplug will listen on and whether it will use SSL or not. This configuration is persisted to %appdata%\Buttplug\config.json.
I think we need still need add some interface to make it easy to get the CA cert installed into the browser, but right now point your browser at the server will work: the web socket server has been swapped to the HttpServer variant, which gives us a test page we can point browsers to to test SSL issues etc. …
> Switching over to HTTPS , with a HTML landing page

- Buttplug/Buttplug.csproj
- Buttplug/Core/ButtplugService.cs
- ButtplugControlLibrary/ButtplugAboutControl.xaml
- ButtplugControlLibrary/ButtplugAboutControl.xaml.cs
- ButtplugControlLibrary/ButtplugControlLibrary.csproj
- ButtplugControlLibrary/LicenseView.xaml
- ButtplugControlLibrary/LicenseView.xaml.cs
- ButtplugTest/Core/ButtplugServerTests.cs
The LICENSE file is now included within the Buttplug assembly so that we don't need to update multiple locations.
Fixes issue #53
> Adding a License Information diaglog off of the About tab

- Buttplug/Core/ButtplugService.cs
- Buttplug/Core/DeviceManager.cs
- Buttplug/Core/DeviceSubtypeManager.cs
- Buttplug/Core/IDeviceSubtypeManager.cs
- ButtplugTest/Core/ButtplugServerTests.cs
- ButtplugTest/Core/TestBluetoothSubtypeManager.cs
- ButtplugTest/Core/TestDeviceSubtypeManager.cs
- ButtplugUWPBluetoothManager/Core/UWPBluetoothManager.cs
- ButtplugUWPGamepadManager/Core/UWPGamepadManager.cs
- ButtplugXInputGamepadManager/Core/XInputGamepadManager.cs
Right now this will only complete after StopScanning is called, because the BLE watcher keeps scanning until there's an error or it's told to stop.
Issue #83
> Adding the ScanningFinished message to the server

- ButtplugWebsockets/ButtplugWebsocketServer.cs
If a stop of the websocket server is somehow requested twice, the
object will be null and can cause a crash. Check to make sure the
server is not null before stopping.
Fixes #128
> fix: Fix null check for websocket server on stop

- ButtplugServerGUI/WebsocketServerControl.xaml.cs
We know that this can happen if 2 instances of the server
are started at the same time. In this case a SocketException
is thown. This change wraps that in a MessageBox.
Other exceptions still throw, and go to sentry.
Fix for #139
> Handling address already in use error

- ButtplugControlLibrary/ButtplugTabControl.xaml.cs
- appveyor.yml
Instead of putting our key into the app all the time, have the CI
stick it in. This will mean less crash reports from people playing
with our code.
Fixes #61
> feat: Replace sentry API in appveyor

- appveyor.yml
Added appveyor config to skip a branch build when a PR on a branch is
sent.
Fixes #146
> build: Make appveyor only build once on PR

- ButtplugKiirooEmulatorGUI/KiirooEmulatorPanel.xaml
- ButtplugKiirooEmulatorGUI/KiirooEmulatorPanel.xaml.cs
- ButtplugKiirooPlatformEmulator/KiirooPlatformEmulator.cs
This change caches issues where the port is already in use,
and there are reads/writes happening whilst the listener is
being shutdown. The later case manifests as the stacktace
in Issue #141
> Adding more error handling to the Kiiroo emulator

- Buttplug.Client.Test/ButtPlugClientTests.cs
- Buttplug.Client/ButtplugWSClient.cs
- app.reg
If the server has no devices, the device list within the deserialized message
will be set to null rather than an empty list. Checking for null avoids the NPE.
> Fixing an issue where no RequestDeviceList() would throw a NPE

- Buttplug.Server.Managers.XInputGamepadManager/XInputGamepadDevice.cs
Fixed SingleMotorVibrateCmd turns off vibrator when speed is 1 #177 by using ushort.MaxValue (2^16-1) instead of 2^16
> Fix for Issue #177

- Buttplug.Client/ButtplugWSClient.cs
- Buttplug.Components.Controls/ButtplugTabControl.xaml.cs
- Buttplug.Components.WebsocketServer/ButtplugWebsocketServer.cs
- Buttplug.Core/ButtplugDevice.cs
- Buttplug.Core/ButtplugLog.cs
- Buttplug.Core/IButtplugDevice.cs
- Buttplug.Core/Messages/Messages.cs
- Buttplug.Server.Managers.UWPBluetoothManager/UWPBluetoothDeviceFactory.cs
- Buttplug.Server.Managers.UWPBluetoothManager/UWPBluetoothDeviceInterface.cs
- Buttplug.Server.Managers.UWPBluetoothManager/UWPBluetoothManager.cs
- Buttplug.Server.Managers.XInputGamepadManager/XInputGamepadDevice.cs
- Buttplug.Server.Test/ButtplugDeviceTests.cs
- Buttplug.Server.Test/TestBluetoothSubtypeManager.cs
- Buttplug.Server.Test/TestDevice.cs
- Buttplug.Server/Bluetooth/ButtplugBluetoothDevice.cs
- Buttplug.Server/Bluetooth/IBluetoothDeviceInterface.cs
- Buttplug.Server/ButtplugService.cs
- Buttplug.Server/DeviceManager.cs
Fixes #176 by telling JSON.net to ignore null values
Fixes #158 by changing the scope of the LogMessage field
Fixes #170 by passing disconnect calls back up to devices
> Correcting the JSON deserialization for arrays

- Buttplug.Apps.WebsocketServerGUI/WebsocketServerControl.xaml
- Buttplug.Apps.WebsocketServerGUI/WebsocketServerControl.xaml.cs
- Buttplug.Components.WebsocketServer/ButtplugWebsocketServer.cs
This adds a connection details section to the server tab to make it quicker and easier to get you're certs installed and get your client attached to the server.
Additionally, the Buttplug Server get noisy if things go wrong during client connection.
> Making it easier to get started with HTTPS

- Buttplug.Apps.WebsocketServerGUI/WebsocketServerControl.xaml.cs
- Buttplug.Components.WebsocketServer/ButtplugWebsocketServer.cs
- Buttplug.Components.WebsocketServer/CertUtils.cs
This fixes #198 by implenting the example @funjack provided.
There were additional issues with the cert chain too.
If neither the local hostname, 'localhost' or the loopback IP are not
resolving correctly, a hostame option can be set in %appdata%\buttplug\config.json. For example:
```
{
"buttplug": {
"server": {
"port": "12345",
"secure": "True",
"maxPing": "0",
"hostname": "foo.example.org"
}
}
}
```
> Correcting the SSL cert  subjects

- Buttplug.Apps.WebsocketServerGUI/WebsocketServerControl.xaml
- Buttplug.Apps.WebsocketServerGUI/WebsocketServerControl.xaml.cs
- Buttplug.Components.Controls/ButtplugTabControl.xaml.cs
- Buttplug.Components.WebsocketServer/Buttplug.Components.WebsocketServer.csproj
- Buttplug.Components.WebsocketServer/ButtplugWebsocketServer.cs
- Buttplug.Components.WebsocketServer/CertUtils.cs
- Buttplug.Components.WebsocketServer/ConnectionEventArgs.cs
- Buttplug.Core/ButtplugLog.cs
- Buttplug.Core/IButtplugLog.cs
- Buttplug.Server/ButtplugServer.cs
Further connections will receive an Error object before the socket is closed.
Additionally, the Server tab now shows the current connection status (and the name of the client connected.
Fixes #196
> Preventing multiple simultaneous connections to the server

- Buttplug.Apps.WebsocketServerGUI/MainWindow.xaml.cs
Until we have dynamic ping adjustments, set ping time to something
slightly more forgiving so we can test over wifi.
Fixes #206
> fix: Change default ping time to 1s

- Buttplug.Server/Bluetooth/Devices/Lovense.cs
The client's now see the device's name rather than the BLE name.
Fixes #203
> Adding friendly names to the Lovense class

- Buttplug.Apps.WebsocketServerGUI/MainWindow.xaml.cs
- Buttplug.Components.Controls/ButtplugLogControl.xaml
- Buttplug.Components.Controls/ButtplugLogControl.xaml.cs
- Buttplug.Components.Controls/ButtplugTabControl.xaml.cs
Fixes #190 by fefaulting to 1000 entries. This can be overriden in the %APPDATA%\Buttplug\config.json file:
```
{
"buttplug": {
"server": {
"port": "12345",
"secure": "False",
},
"log": {
"max": "5000"
}
}
}
```
Fixes #185 by allowing multi-line selection and handling Ctrl+C to copy the log entries to the clipboard.
Fixes #187 by adding a Clear Log button, which clears the log list.
> Improving the Log tab

- Buttplug.Core/Messages/Messages.cs
The schema states that this should contain a string named Command rather than a uint named Position. To handle this is a non-breaking way, the Position setter/getter has been preseved, but stores the uint value in the Command string.
Fixes #221
> Correcting the KiirooCmd message

- Buttplug.Server.Managers.UWPBluetoothManager/UWPBluetoothDeviceInterface.cs
- Buttplug.Server/Bluetooth/BluetoothSubtypeManager.cs
- Buttplug.Server/Bluetooth/ButtplugBluetoothDevice.cs
- Buttplug.Server/Bluetooth/Devices/FleshlightLaunch.cs
- Buttplug.Server/Bluetooth/Devices/Kiiroo.cs
- Buttplug.Server/Bluetooth/Devices/Lovense.cs
- Buttplug.Server/Bluetooth/Devices/MagicMotion.cs
- Buttplug.Server/Bluetooth/Devices/Vibratissimo.cs
- Buttplug.Server/Bluetooth/Devices/VorzeA10Cyclone.cs
- Buttplug.Server/Bluetooth/Devices/WeVibe.cs
- Buttplug.Server/Bluetooth/IBluetoothDeviceInterface.cs
- Buttplug.Server/Buttplug.Server.csproj
This adds support for the WeVibe Pivot and Verge (and I'm pretty sure it just needs the names of the other devices in the WeVibe family to get them supported too).
The order of the GATT characteristics appeared to differ depending on whether I was using gatt-tool or the UWP interface, so as a side effect this fixes #108
Partial fix for #225
> Wevibe support

- Buttplug.Server/Bluetooth/Devices/WeVibe.cs
The 4 Plus works with the current code, assuming the Nova does too.
> feat: Add more WeVibe product names

- Buttplug.Components.Controls/ButtplugDeviceControl.xaml.cs
- Buttplug.Core/ButtplugDevice.cs
- Buttplug.Core/IButtplugDevice.cs
- Buttplug.Server/DeviceManager.cs
For the Kiiroo ans XInput interfaces, the device list has been updated to leave the devices on the list, but with a (dissconnected) note next to them. If they reappear, they will continue to be used (assuming they are still selected).
Fixes #249
> Making devices that disappear, reappear with the same ID

- Buttplug.Apps.GameVibrationRouter.GUI/MainWindow.xaml
- Buttplug.Apps.GameVibrationRouter.GUI/MainWindow.xaml.cs
- Buttplug.Apps.KiirooEmulatorGUI/MainWindow.xaml
- Buttplug.Apps.KiirooEmulatorGUI/MainWindow.xaml.cs
- Buttplug.Apps.WebsocketServerGUI/Buttplug.Apps.WebsocketServerGUI.csproj
- Buttplug.Apps.WebsocketServerGUI/MainWindow.xaml
- Buttplug.Apps.WebsocketServerGUI/MainWindow.xaml.cs
- Buttplug.Apps.WebsocketServerGUI/WebsocketServerControl.xaml
- Buttplug.Apps.WebsocketServerGUI/WebsocketServerControl.xaml.cs
- Buttplug.Components.Controls/Buttplug.Components.Controls.csproj
- Buttplug.Components.Controls/ButtplugAboutControl.xaml
- Buttplug.Components.Controls/ButtplugAboutControl.xaml.cs
- Buttplug.Components.Controls/ButtplugConfig.cs
- Buttplug.Components.Controls/ButtplugLogControl.xaml.cs
- Buttplug.Components.Controls/ButtplugTabControl.xaml
- Buttplug.Components.Controls/ButtplugTabControl.xaml.cs
- Buttplug.Components.KiirooPlatformEmulator/KiirooPlatformEmulator.cs
- Buttplug.Core/Buttplug.Core.csproj
- Buttplug.Core/ButtplugLog.cs
- Buttplug.Core/IButtplugLog.cs
- Buttplug.Core/LogExceptionEventArgs.cs
This change also includes better error reporting: the last error is displayed on the WebSocket tab and notifications of errors are raised via the Windows Toast system.
Additionally, the gap in the tabs left by the Devices tab has been fixed.
> Making SSL the default operating mode for WebSockets

- Buttplug.Apps.WebsocketServerGUI/WebsocketServerControl.xaml.cs
- Buttplug.Components.WebsocketServer/ButtplugWebsocketServer.cs
This should quite down the "Not GET" notices.
> Suppressing websocket exceptions that don't close the connections

- Buttplug.Apps.KiirooEmulatorGUI/MainWindow.xaml.cs
- Buttplug.Apps.WebsocketServerGUI/WebsocketServerControl.xaml.cs
- Buttplug.Components.KiirooPlatformEmulator/KiirooPlatformEmulator.cs
Clicking the toast messages now raises the GUI to the front.
Disposed HttpListeners are now handled as closed connections.
> Toast click handling and more Kiiroo exception handling

- Buttplug.Components.Controls/ButtplugAboutControl.xaml.cs
- Buttplug.Server.Managers.UWPBluetoothManager/UWPBluetoothManager.cs
Use UWP functions to see if we even have a viable adapter to use and
write information to the log about it.
> chore: Add basic adapter detection to UWP Bluetooth Manager Startup

- Buttplug.Apps.WebsocketServerGUI/WebsocketServerControl.xaml.cs
- Buttplug.Client/Buttplug.Client.nuspec
- Buttplug.Components.Controls/Buttplug.Components.Controls.nuspec
- Buttplug.Core/Buttplug.Core.nuspec
- Buttplug.Server.Managers.UWPBluetoothManager/Buttplug.Server.Managers.UWPBluetoothManager.nuspec
- Buttplug.Server.Managers.XInputGamepadManager/Buttplug.Server.Managers.XInputGamepadManager.nuspec
- CHANGELOG.md
- LICENSE
- README.md
We're getting a lot of weird exceptions for Websockets even when the
connection works. This can lead to the notification toaster popping
constantly, which will confuse the user. Only pop the toaster if we
don't connect right after the exception is thrown.
Fixes #280
> fix: Only pop toaster if we haven't connected to websocket

- Buttplug.Apps.WebsocketServerGUI/WebsocketServerControl.xaml.cs
Right now we're crashing on intermittent cryptographic exceptions
thrown on CI. This shouldn't crash the GUI, but should be shown in the
GUI.
Fixes #277
> fix: Catch cryptographic exception on server startup and show in GUI

- Buttplug.Apps.WebsocketServerGUI/WebsocketServerControl.xaml.cs
Currently the "not get" exception supression timer is 500ms, which is
apparently too slow for some cases. Up it to 1s.
Fixes #287
> fix: Extend "not get" supression timer

- Buttplug.Apps.GameVibrationRouter.GUI/ProcessTab.xaml
We have logic to enable the process select button, but it's enabled on
start. Clicking it without a selected process causes a crash.
Fixes #295
> fix: Game Router process select button should be disabled on start

- Buttplug.Apps.KiirooEmulatorGUI/Buttplug.Apps.KiirooEmulatorGUI.csproj
- Buttplug.Apps.WebsocketServerGUI/Buttplug.Apps.WebsocketServerGUI.csproj
Fixes "namespace name 'UI' does not exist in the namespace 'Windows'" compile time errors.
> Explicitly add references to Windows RT API

- Buttplug.Server/Bluetooth/Devices/WeVibe.cs
Yet another name for the WeVibe4.
Fixes #309
> feat: Add Cougar to WeVibe device name list

- Buttplug.Apps.ExampleClientGUI/ExampleClientPanel.xaml.cs
- Buttplug.Client.Test/ButtPlugClientTests.cs
- Buttplug.Client/ButtplugWSClient.cs
- Buttplug.Components.WebsocketServer/CertUtils.cs
This sets the ignore subject and ignore unknown certificates flags on WebSocket4Net.
Unfortunatly our WebSocketServer library does not allow for a X509Chain to be provided and WebSocket4Net requires
the chain to be valid (even if the root is self signed). To avoid this breaking us further, the cert generation now skips the CA and only gnerates a single self-signed cert. For upgrade purposes, any existing CA+Cert combos wil be removed.
Fixes #316
> Adding an 'ignore cert errors' flag to the WSClient

- Buttplug.Client.Test/ButtPlugClientTests.cs
- Buttplug.Client/ButtplugWSClient.cs
This means consumers of the library do not need to manually set the message IDs at all now.
Fixes #318
> ButtplugWSClient::SendMessage() always increments the msgID

- Buttplug.Apps.ExampleClientGUI/ExampleClientPanel.xaml.cs
- Buttplug.Client.Test/ButtPlugClientTests.cs
- Buttplug.Client/ButtplugWSClient.cs
This means that during Connect() any devices already connected to the buttplug server will cause DeviceAdded events to be fired. This will include any devices that may have already been seen in the case of a reconnect (if the connection has dropped anything could have happened to the server, therefore the device list is purged and all devices are readded from scratch). As this is now called for you, the RequestDeviceList() method has been removed.
The internal device list is now accessible via a C# style getter Devices rather than the previous getDevices() method.
The nextMsgId getter has also been renamed to NextMsgId for consistency.
> ButtplugWSClient now requests the device list on connect

- .gitignore
- Buttplug.Client/Buttplug.Client.csproj
- Buttplug.Client/ButtplugWSClient.cs
- appveyor.yml
At some point, between WebSocket4Net 0.15.0 and 0.15.2, the dependency on SuperSocket.ClientEngine moved to SuperSocket.ClientEngine.Core (a straight rename), which meant that because we were still dependent of SuperSocket.ClientEngine we got 2 conflicting libraries.
Removing our explicit dependency on SuperSocket.ClientEngine means we now get whatever WebSocket4Net needs and no more.
> Correcting a dependency clash in the Buttplug.Client package

- Buttplug.Server/Bluetooth/Devices/Lovense.cs
Lovense sure does love changing device names.
Fixes #348
> chore: Add LVS-Edge38 as new device name

- Buttplug.Server.Test/Bluetooth/Devices/KiirooOnyx2Tests.cs
- Buttplug.Server.Test/Buttplug.Server.Test.csproj
- Buttplug.Server/Bluetooth/BluetoothSubtypeManager.cs
- Buttplug.Server/Bluetooth/Devices/FleshlightLaunch.cs
It turns out the protocol for the Onyx2 is identical to the
Fleshlight Launch, with the exception that the handshake
byte is written to the Cmd handle instead of the Tx.
This adds the characteristic set to the existing Launch
protocol class rather than duplicating it.
Fixes #320
> feat: Onyx2 support

- Buttplug.Server.Managers.UWPBluetoothManager/UWPBluetoothDeviceInterface.cs
- Buttplug.Server.Test/TestBluetoothDeviceInterface.cs
- Buttplug.Server/Bluetooth/BluetoothNotifyEventArgs.cs
- Buttplug.Server/Bluetooth/Devices/Lovense.cs
- Buttplug.Server/Bluetooth/IBluetoothDeviceInterface.cs
The existing Bluetooth interface doesn't quite support notify. SubscribeToUpdates() will tell the server you're interested, but nothing ever subscribes to the event to receive the messages. This adds an event (BluetoothNotifyReceived) to fill that hole. Conversion to a byte array is handled internally for convenience. (Won't work for indexed characteristics as things stand, but I don't have a device to test that with anyway.)
And then that's used to fix Lovense device identification. Since read performs quickly on supported devices, that's done first, and if that fails it waits for a bit to see if a message will come in. It's usually much faster than half a second, but the timing does vary, so I used a loop rather than a fixed delay time.
At least for the device I have, subscribing to …
> Bluetooth capability addition and Lovense fix

- Buttplug.Apps.ServerGUI/ServerControl.xaml.cs
- Buttplug.Server.Connectors.WebsocketServer/ButtplugWebsocketServer.cs
This change fixes #467 and also adds better exception handling to the websocket server startup.
> fix: Adding websocket Stop() call

- Buttplug.Server/Bluetooth/Devices/KiirooGen2Vibe.cs
We already had support for the Pornhub branded version of this device.
This change adds the Kiiroo branded version's BLE name to the driver.
> feat: Adding Kiiroo Titan support

- Buttplug.Server.Managers.UWPBluetoothManager/UWPBluetoothDeviceInterface.cs
- Buttplug.Server.Managers.UWPBluetoothManager/UWPBluetoothManager.cs
- Buttplug.Test/Server/Bluetooth/Devices/KiirooOnyx1Tests.cs
- Buttplug/Server/Bluetooth/Devices/Lovense.cs
If a characteristic has indicate and/or notify, subscribe to that
characteristic. Also update Lovense to deal correctly with reads
versus notifications.
Fixes #417
> chore: Add indicate subscriptions to UWP devices

- appveyor.yml
Due to the inclusion of the dev branch, plus the way appveyor checks
things out, things can get confused when a PR comes in for the dev
branch. Make sure we only look for tags on master.
Fixes #552
> build: Only let appveyor search for git tags on master

- Buttplug/Server/Bluetooth/Devices/MagicMotion.cs
Add support for LoveLife Krush kegel exerciser to the MagicMotion server device because they share service and characteristic UUID.
> Add support for LoveLife Krush

- Buttplug.Server.Managers.UWPBluetoothManager/UWPBluetoothDeviceInterface.cs
- Buttplug.Server.Managers.UWPBluetoothManager/UWPBluetoothManager.cs
This was an issue discovered with the MagicMotion Vini
which wasn't showing up due to not getting a service
returned. The service was present and useable when
GetServicesAsync() was called instead.
Additioanlly:
- more logging is now emitted from the UWP BLE manager
when this sort of error occures
- only one attempt to create a connection to a specific
device happens at once now (previously multiple threads
could be launched to create a connection for a single
device).
> fix: GetGattServicesForUuidAsync() failed to find services

- Buttplug/Devices/Protocols/WeVibeProtocol.cs
This should also work for the Moxie; however, these
new devices seem to require pairing before they'll
respond. I haven't worked out that magic yet though,
but once paired the device does not required the
pairing to be retained (the adapter address must be
stored on the device).
To get the Vector into pairing mode, hold down the
power button for 5 seconds (it'll buzz, but don't release)
then hit pair in Bluetooth LE explorer app.
I'll investigate the pairing logic in that app at some
point soon.
> feat: Adding protocol support for WeVibe Vector

- Buttplug.Test/Devices/Protocols/YououTests.cs
- Buttplug/Devices/Protocols/YououProtocol.cs
The _vibrationSpeed variable isn't updated, so on stop
the device already thinks it's stopped.
> fix: Youou never sends vibe speeds of 0

- Buttplug/Devices/Protocols/KiirooGen21Protocol.cs
This change still requires the updated device config, but right now the device config alone will present the Onyx+ as a vibe.
> feat: Add support for Onyx+

- Buttplug.Test/Buttplug.Test.csproj
netcoreapp was [replaced](https://learn.microsoft.com/en-us/dotnet/standard/frameworks#supported-target-frameworks) with net since v5.
> use correct framework
