buttplugio/buttplug-csharp

- Buttplug/Core/ButtplugJSONMessageParser.cs
- Buttplug/Core/ButtplugService.cs
- ButtplugTest/Core/ButtplugJsonMessageParserTests.cs
- ButtplugTest/Messages/ButtplugMessage.cs
- ButtplugWebsockets/ButtplugWebsocketServerBehavior.cs
The top level element is intended to be an array not an object.
This code still only handles a single message right now.
>  Correcting the handling of JSON from the websocket.

- LICENSE
Add JetBrains.Annotations, OpenCover, SharpRaven, and
CommandLineParser licenses.
Fixes #100
> doc: Update license file

- Buttplug/Buttplug.csproj
- Buttplug/Core/ButtplugJSONMessageParser.cs
- Buttplug/Messages/Messages.cs
- Buttplug/app.config
- Buttplug/packages.config
- ButtplugCLI/App.config
- ButtplugControlLibrary/ButtplugControlLibrary.csproj
- ButtplugControlLibrary/app.config
- ButtplugKiirooEmulatorGUI/ButtplugKiirooEmulatorGUI.csproj
- ButtplugServerGUI/App.config
- ButtplugTest/app.config
- ButtplugUWPBluetoothManager/app.config
- ButtplugUWPGamepadManager/app.config
- ButtplugWebsockets/ButtplugWebsockets.csproj
- ButtplugWebsockets/app.config
- ButtplugXInputGamepadManager/app.config
- LICENSE
This time using the NJsonSchema Library under MIT license.
Fixes #101
> Re-Adding schema validation

- Buttplug/Bluetooth/Devices/Lovense.cs
- ButtplugUWPBluetoothManager/Core/ButtplugBluetoothDeviceFactory.cs
- ButtplugUWPBluetoothManager/Core/UWPBluetoothManager.cs
Also some extra trace logging to make adding new BLE devices easier.
> Adding Ambi support

- LICENSE
> doc: Remove websocket-sharp license, add websocketlistener license

- Buttplug.Core/Buttplug.Core.nuspec
- Buttplug.Core/Properties/AssemblyInfo.cs
- Buttplug.sln
- appveyor.yml
Small build configuration fixes, and adding nuget to appveyor.
> Add Nuget to appveyor

- Buttplug.Client.Test/ButtPlugClientTests.cs
- Buttplug.Client/Buttplug.Client.csproj
- Buttplug.Client/ButtplugWSClient.cs
- Buttplug.Client/ErrorEventArgs.cs
- Buttplug.Components.WebsocketServer/ButtplugWebsocketServer.cs
Brings in @blackspherefollower's ping error handling patch, with a couple of fix commits on top for fixing a race in shutdown.
> Better ping handling plus less hanging

- appveyor.yml
> build: Readd branch restriction

- Buttplug.Apps.WebsocketServerGUI/WebsocketServerControl.xaml
- Buttplug.Apps.WebsocketServerGUI/WebsocketServerControl.xaml.cs
- Buttplug.Components.WebsocketServer/ButtplugWebsocketServer.cs
Now you can kick the client from the server GUI.
Fixes #205
> Adding disconnect button

- Buttplug.Client/ButtplugWSClient.cs
I've seen some socket aborted exceptions thrown on disconnect. We should be handling these errors.
> Reinforcing the client's disconnect method

- Buttplug.Apps.KiirooEmulatorGUI/MainWindow.xaml
- Buttplug.Apps.WebsocketServerGUI/WebsocketServerControl.xaml
- Buttplug.Apps.WebsocketServerGUI/WebsocketServerControl.xaml.cs
- Buttplug.Client/ButtplugWSClient.cs
- Buttplug.Components.Controls/ButtplugLogControl.xaml.cs
- Buttplug.Components.Controls/ButtplugTabControl.xaml.cs
- Buttplug.Components.WebsocketServer/ButtplugWebsocketServer.cs
- Buttplug.Core/ButtplugJsonMessageParser.cs
- Buttplug.Server.Managers.UWPBluetoothManager/UWPBluetoothManager.cs
- Buttplug.Server.Managers.XInputGamepadManager/XInputGamepadManager.cs
- Buttplug.Server/ButtplugServer.cs
- Buttplug.Server/DeviceManager.cs
- Buttplug.Server/DeviceSubtypeManager.cs
Adds a "localhost only" checkbox, and displays all interfaces that the server is listening on.
Moves some Trace and Debug messages to more appropriate levels.
> Loopback only connections and logging refactors

- Buttplug.Apps.WebsocketServerGUI/WebsocketServerControl.xaml.cs
- Buttplug.Components.Controls/ButtplugAboutControl.xaml
- Buttplug.Components.WebsocketServer/ButtplugWebsocketServer.cs
- Buttplug.Server.Managers.UWPBluetoothManager/UWPBluetoothDeviceFactory.cs
- Buttplug.Server/Bluetooth/BluetoothSubtypeManager.cs
- Buttplug.Server/Bluetooth/Devices/MagicMotion.cs
- Buttplug.Server/Buttplug.Server.csproj
Bug fixes:
1. The images were missing from the about page
2. The Stop button shutdown the WS server, but left exisiting connections open
3. All interfaces were listed even in loopback only mode
Adding support for Magic Motion Smart Mini Vibe
> Bug fixes and Magic Motion support

- Buttplug.Server.Managers.UWPBluetoothManager/UWPBluetoothDeviceFactory.cs
- Buttplug.Server.Managers.UWPBluetoothManager/UWPBluetoothManager.cs
> Attempted fix for disappearing BLE advertisment

- Buttplug.Components.Controls/ButtplugAboutControl.xaml
Yes that was actually a problem.
> fix: Fix spelling of "buttplugging"

- Buttplug.Server/Bluetooth/Devices/WeVibe.cs
> Adding the Ditto and Wish IDs

- Buttplug.Apps.XInputInjector.GUI/MainWindow.xaml.cs
- buttplug-installer.iss
Fixing the input injector process issue.
> Install all executables in output directories

- Buttplug.Server/Bluetooth/BluetoothSubtypeManager.cs
- Buttplug.Server/Bluetooth/Devices/Lovense.cs
Just needs a new set of service/characteristic IDs in the Lovense
class. We really gotta clean up our groupings on this. :/
Fixes #251
> feat: Add Lovense Domi Support

- Buttplug.Apps.GameVibrationRouter.GUI/MainWindow.xaml
- Buttplug.Apps.KiirooEmulatorGUI/KiirooEmulatorPanel.xaml
- Buttplug.Apps.KiirooEmulatorGUI/MainWindow.xaml
- Buttplug.Apps.WebsocketServerGUI/MainWindow.xaml
- Buttplug.Apps.WebsocketServerGUI/WebsocketServerControl.xaml
- Buttplug.Components.Controls/ButtplugAboutControl.xaml
Make sure everything resizes and scrolls correctly, set min
width/height for applications.
Fixes #264
> chore: Clean up controls and app layouts

- Buttplug.Components.Controls/ButtplugAboutControl.xaml.cs
- CHANGELOG.md
Don't rely on presence of hyphen for version parsing.
Fixes #289
> fix: Fix ArgumentOutOfBoundException in updater

- Buttplug.Server/Bluetooth/BluetoothSubtypeManager.cs
- Buttplug.Server/Bluetooth/Devices/Youcups.cs
- Buttplug.Server/Buttplug.Server.csproj
Added support for Youcups Warrior II masturbator
> Added support for Youcups Warrior II masturbator

- Buttplug.Apps.WebsocketServerGUI/Buttplug.Apps.WebsocketServerGUI.csproj
Previously this was loading multiple Windows SDKs and getting conflicts. This resolves those errors.
> Correct the reference resolution for the WebsocketServerGUI project

- Buttplug.Server/Bluetooth/BluetoothSubtypeManager.cs
- Buttplug.Server/Bluetooth/Devices/Lovense.cs
They keep changing it, so do we. :(
Fixes #322
> fix: Add new Name/UUIDs for Lovense Edge

- Buttplug.Components.WebsocketServer/CertUtils.cs
- Buttplug.Server.Managers.XInputGamepadManager/XInputGamepadDevice.cs
- Buttplug.Server/Bluetooth/BluetoothSubtypeManager.cs
- Buttplug.Server/Bluetooth/Devices/Lovense.cs
- Buttplug.Server/Bluetooth/Devices/OhMiBodFuse.cs
- appveyor.yml
Also fixing some non-returned errors in the xinput driver
> Adding OhMiBod Fuse support

- Buttplug.Server.Managers.ErosTek/ETSerialManager.cs
This limits the scanning to 5 attempts.
Fixes #334
> Adding a loop counter to ETSerialManager

- Buttplug.Server.Test/Bluetooth/Devices/LovenseTests.cs
- Buttplug.Server/Bluetooth/BluetoothSubtypeManager.cs
- Buttplug.Server/Bluetooth/Devices/Lovense.cs
New version of Lush
New Domi name match
Fixes #341
> Adding yet more Lovense IDs

- Buttplug.Server.Test/Bluetooth/Devices/WeVibeTests.cs
- Buttplug.Server/Bluetooth/Devices/KiirooGen2Vibe.cs
- Buttplug.Server/Bluetooth/Devices/WeVibe.cs
See https://gist.github.com/bnm12/fcdcef291a500bf51cef734aa1830e4d
> Adding support for individual vibrator control in dual motor WeVibes

- Buttplug.Apps.GameVibrationRouter.GUI/MainWindow.xaml.cs
- Buttplug.Apps.GameVibrationRouter.GUI/VibeGraphTab.xaml.cs
- Buttplug.Apps.GameVibrationRouter.Interface/ButtplugGameVibrationRouterInterface.cs
- Buttplug.Apps.KiirooEmulatorGUI.Test/KiirooGUITest.cs
- Buttplug.Components.Controls/ButtplugDeviceControl.xaml.cs
- Buttplug.Components.Controls/ButtplugDeviceInfo.cs
- Buttplug.Components.Controls/ButtplugTabControl.xaml.cs
- Buttplug.Server.Managers.ErosTek/Buttplug.Server.Managers.ETSerialManager.csproj
Lots of warnings left over from the GVR push. Fixing those up.
> chore: Fix warnings

- Buttplug.Components.Controls/Buttplug.Components.Controls.csproj
- Buttplug.Components.Controls/ButtplugTabControl.xaml.cs
- Buttplug.Server.Managers.HidManager/Buttplug.Server.Managers.HidManager.csproj
- Buttplug.Server.Managers.HidManager/Devices/CycloneX10.cs
- Buttplug.Server.Managers.HidManager/HidButtplugDevice.cs
- Buttplug.Server.Managers.HidManager/HidDeviceFactory.cs
- Buttplug.Server.Managers.HidManager/HidManager.cs
- Buttplug.Server.Managers.HidManager/IHidDeviceInfo.cs
- Buttplug.Server.Managers.HidManager/Properties/AssemblyInfo.cs
- Buttplug.Server.Managers.HidManager/app.config
- Buttplug.Server.Managers.HidManager/packages.config
- Buttplug.sln
This may or may not have been the precursor to the Vorze A10 Cyclone. Assuming that it might be, it is backwards compatible with the VorzeA10CycloneCmd
> feat: Cyclone X10 support

- Buttplug.Apps.ExampleClientGUI/ExampleClientPanel.xaml.cs
- Buttplug.Core/Messages/Messages.cs
- Buttplug.Server.Managers.UWPBluetoothManager/UWPBluetoothDeviceFactory.cs
- Buttplug.Server.Test/Bluetooth/Devices/FleshlightLaunchTests.cs
- Buttplug.Server.Test/Bluetooth/Devices/KiirooGen2VibeTests.cs
- Buttplug.Server.Test/Bluetooth/Devices/KiirooTests.cs
- Buttplug.Server.Test/Bluetooth/Devices/LovenseTests.cs
- Buttplug.Server.Test/Bluetooth/Devices/MagicMotionTests.cs
- Buttplug.Server.Test/Bluetooth/Devices/VibratissimoTests.cs
- Buttplug.Server.Test/Bluetooth/Devices/VorzeSATests.cs
- Buttplug.Server.Test/Bluetooth/Devices/WeVibeTests.cs
- Buttplug.Server.Test/Bluetooth/Devices/YoucupsTests.cs
- Buttplug.Server.Test/Util/BluetoothDeviceTestUtils.cs
- Buttplug.Server/Bluetooth/Devices/FleshlightLaunch.cs
- Buttplug.Server/Bluetooth/Devices/Kiiroo.cs
- Buttplug.Server/Bluetooth/Devices/KiirooGen2Vibe.cs
- Buttplug.Server/Bluetooth/Devices/Lovense.cs
- Buttplug.Server/Bluetooth/Devices/MagicMotion.cs
- Buttplug.Server/Bluetooth/Devices/Vibratissimo.cs
- Buttplug.Server/Bluetooth/Devices/VorzeSA.cs
- Buttplug.Server/Bluetooth/Devices/WeVibe.cs
- Buttplug.Server/Bluetooth/Devices/Youcups.cs
Cleaning up log messages and repeated code from the test overhaul.
> Test cleanup

- Buttplug.Server.Managers.UWPBluetoothManager/UWPBluetoothDeviceInterface.cs
- Buttplug.Server.Test/Bluetooth/Devices/MysteryVibeTests.cs
- Buttplug.Server.Test/Buttplug.Server.Test.csproj
- Buttplug.Server.Test/TestBluetoothDeviceInterface.cs
- Buttplug.Server.Test/Util/BluetoothDeviceTestUtils.cs
- Buttplug.Server/Bluetooth/BluetoothSubtypeManager.cs
- Buttplug.Server/Bluetooth/Devices/MysteryVibe.cs
Add Mysteryvibe Crescendo support
> WIP: Code cleanup and Crescendo support

- Buttplug.Server.Test/Bluetooth/Devices/LiBoTest.cs
- Buttplug.Server.Test/Buttplug.Server.Test.csproj
- Buttplug.Server/Bluetooth/BluetoothSubtypeManager.cs
- Buttplug.Server/Bluetooth/Devices/LiBo.cs
- Buttplug.Server/Bluetooth/Devices/MysteryVibe.cs
Updating #373 to land before next release.
> Libo Support

- Buttplug.Apps.GameVibrationRouter.GUI/Buttplug.Apps.GameVibrationRouter.GUI.csproj
- Buttplug.Apps.GameVibrationRouter.GUI/MainWindow.xaml.cs
- Buttplug.Apps.GameVibrationRouter.GUI/VibeConfigTab.xaml
- Buttplug.Apps.GameVibrationRouter.GUI/VibeConfigTab.xaml.cs
- Buttplug.Components.Controls/ButtplugTabControl.xaml
- Buttplug.Components.Controls/ButtplugTabControl.xaml.cs
> feat: Early vibration multiplier feature implemented

- Buttplug.Apps.GameVibrationRouter.GUI/Buttplug.Apps.GameVibrationRouter.GUI.csproj
- Buttplug.Apps.ServerGUI/Buttplug.Apps.ServerGUI.csproj
- appveyor.yml
Trying to figure out why appveyor is failing on tests but only on master?
> More CI Fixes

- Buttplug/Server/Bluetooth/BluetoothSubtypeManager.cs
- Buttplug/Server/Bluetooth/Devices/Picobong.cs
Tested with example code and the Picobong Diver
> feat: Adding support for Picobong devices

- Buttplug.Test/Buttplug.Test.csproj
- Buttplug.Test/Server/Bluetooth/Devices/PicobongTests.cs
- Buttplug.Test/Server/Bluetooth/Devices/VorzeBachTests.cs
- Buttplug.Test/Server/Bluetooth/Devices/VorzeSATests.cs
- Buttplug.Test/Server/Bluetooth/Devices/VorzeUFOSATests.cs
- Buttplug/Server/Bluetooth/Devices/VorzeSA.cs
Adding support for Vorze Bach.
Also adding missing tests for Picobong.
> feat: Vorze Bach support

- Buttplug.Test/Buttplug.Test.csproj
- Buttplug.Test/Server/Bluetooth/Devices/CuemeTests.cs
- Buttplug.Test/Server/Bluetooth/Devices/MagicMotionTests.cs
- Buttplug/Server/Bluetooth/BluetoothSubtypeManager.cs
- Buttplug/Server/Bluetooth/Devices/Cueme.cs
- Buttplug/Server/Bluetooth/Devices/MagicMotion.cs
Adding support for the Cueme underwear and fixing the MagicMotion max speeds
> Cueme support and MagicMotion fixes

- Buttplug/Devices/Protocols/MagicMotionProtocol.cs
- dependencies/buttplug-device-config/buttplug-device-config.yml
* Magic Fugu
* Magic Vini
Also tested Magic Kegel Master Gen2, but that worked without changes.
> feat: Adding support for 2 more MagicMotion devices

- Buttplug.Test/Devices/Protocols/KiirooGen21VibeTests.cs
- Buttplug/Devices/Configuration/DeviceConfigurationManager.cs
- Buttplug/Devices/Protocols/KiirooGen21VibeProtocol.cs
- dependencies/buttplug-device-config/buttplug-device-config.yml
This looks a lot like the Onyx2.1 protocol, so bets are
that this is just the first of mutiple gen2.1 Kiiroo vibes.
> feat: Add support for the Kiiroo Cliona

- Buttplug.Test/Devices/Protocols/RealovTests.cs
- Buttplug/Devices/Configuration/DeviceConfigurationManager.cs
- Buttplug/Devices/Protocols/RealovProtocol.cs
- dependencies/buttplug-device-config/buttplug-device-config.yml
Currently there are only 2 (LYDIA I and IRENA I) and both have been tested
> feat: Adding support for Realov devices

- Buttplug/Devices/Protocols/MagicMotionProtocol.cs
> feat: Adding support for 3 new MagicMotion devices

- Buttplug.Server.Managers.UWPBluetoothManager/UWPBluetoothDeviceInterface.cs
- Buttplug/Devices/Protocols/VorzeSAProtocol.cs
- dependencies/buttplug-device-config/buttplug-device-config.json
- dependencies/buttplug-device-config/buttplug-device-config.yml
I wrote the code for Vorze PistonSA in my project and I'm donating it.
If you like, please use it.
If there are any inconsistencies, I will fix them, so please point them out.
> feat: Adding support for Vorze PistonSA
